# Generated by Django 5.1.1 on 2024-09-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0002_userex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
