# Generated by Django 5.1.1 on 2024-09-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0004_alter_serviceprovider_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
