# Generated by Django 5.1.1 on 2024-09-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0007_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='status',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userEx.category')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userEx.serviceprovider')),
                ('subcategories', models.ManyToManyField(to='userEx.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('introduction', models.TextField()),
                ('company_founded_date', models.DateField()),
                ('payment_methods', models.CharField(max_length=200)),
                ('service_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userEx.serviceprovider')),
                ('services_included', models.ManyToManyField(to='userEx.subcategory')),
            ],
        ),
    ]
