# Generated by Django 5.1.1 on 2024-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0009_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='spprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
