# Generated by Django 5.1.1 on 2024-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEx', '0014_subscriptionplan_userex_is_subscribed_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.CharField(default='monthly', max_length=10),
        ),
    ]
